Add util ci function

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -303,4 +303,48 @@ function run_tmux() {
     fi
 }
 
+function reload() {
+    source ~/.zshrc
+}
+
+notify() {
+    echo $1
+    osascript -e "display notification \"$1\""
+}
+
+ci_check() {
+    local branch_name="$1"
+
+    while [[ "$(hub ci-status $branch_name 2>/dev/null)" = "pending" ]]; do
+        echo -n '.'
+        sleep 10
+    done
+
+    local st=$(hub ci-status $branch_name 2>&1)
+    case $st in
+        "success" )
+            notify "$(echo "CI Succeeded \U1F646")"
+            ;;
+        "error" )
+            notify "$(echo "CI Failed \U1F645")"
+            ;;
+        * )
+            echo $st
+            exit 1
+            ;;
+    esac
+
+    local url=$(hub ci-status $branch_name -v | awk '{ print $2 }')
+    echo -n "open $url ? [Y/n] "
+    read answer
+
+    case $answer in
+        "Y" | "y" )
+            open "$url"
+            ;;
+        * )
+            ;;
+    esac
+}
+
 run_tmux
